In [1]:
import numpy as np
import os
import pandas as pd
home_path = os.path.expanduser("~") + '/'
from utils.load_data import *
from utils.info_params import *

OpenCV is built with OpenMP support. This usually results in poor performance. For details, see https://github.com/tensorpack/benchmarks/blob/master/ImageNet/benchmark-opencv-resize.py


In [2]:
data_file_name = home_path + "data/ccxt/preprocessing_data/ETH_USDT_binance_1h.csv"
normalize_data = 'z_score'
normalize_data_idx = True

In [3]:
df = pd.read_csv(data_file_name)
df

Unnamed: 0     Timestamp    Open    High     Low   Close       Volume  \
0             124  1.503389e+12  300.35  302.26  296.00  299.82    516.27772   
1             125  1.503392e+12  301.09  310.24  300.30  308.33    557.58036   
2             126  1.503396e+12  308.33  313.16  305.40  310.24    537.67538   
3             127  1.503400e+12  309.40  312.93  306.97  308.03    564.59159   
4             128  1.503403e+12  311.16  311.24  304.53  311.23    671.88512   
5             129  1.503407e+12  306.66  310.27  306.65  307.08    404.77411   
6             130  1.503410e+12  307.08  309.53  301.48  305.48    393.09732   
7             131  1.503414e+12  305.48  309.85  304.88  308.39    287.07405   
8             132  1.503418e+12  305.08  320.24  305.08  317.74    455.53867   
9             133  1.503421e+12  316.24  320.76  312.00  312.07    247.04944   
10            134  1.503425e+12  313.99  315.25  309.60  310.77    378.04740   
11            135  1.503428e+12  310.77  314.83  307.03  307.03    223.61559   
12            136  1.503432e+12  307.03  312.00  305.66  310.19    251.25776   
13            137  1.503436e+12  310.27  311.99  305.08  309.16    277.13507   
14            138  1.503439e+12  309.16  313.10  309.16  310.61    302.25672   
15            139  1.503443e+12  310.61  313.99  306.90  309.80    371.40685   
16            140  1.503446e+12  312.25  313.99  309.41  312.45    202.93145   
17            141  1.503450e+12  310.56  314.82  310.56  312.67    170.07430   
18            142  1.503454e+12  314.80  316.27  312.66  314.15    482.22957   
19            143  1.503457e+12  315.71  319.78  312.98  317.26    233.09815   
20            144  1.503461e+12  315.45  324.99  315.45  323.00    432.60958   
21            145  1.503464e+12  320.73  323.26  316.51  316.74    262.04246   
22            146  1.503468e+12  316.74  323.29  315.35  322.10    435.21335   
23            147  1.503472e+12  319.77  323.30  318.04  319.06    246.19782   
24            148  1.503475e+12  319.06  323.19  318.02  322.07    390.97267   
25            149  1.503479e+12  319.74  324.51  319.74  320.74    312.13542   
26            150  1.503482e+12  320.74  324.21  319.73  319.74    260.26644   
27            151  1.503486e+12  319.74  323.07  318.95  319.20    322.49950   
28            152  1.503490e+12  319.20  322.00  313.75  316.96    598.91827   
29            153  1.503493e+12  316.96  318.96  314.50  316.00    686.70237   
...           ...           ...     ...     ...     ...     ...          ...   
17614       17752  1.567184e+12  168.67  168.83  167.65  167.73   5725.50176   
17615       17753  1.567188e+12  167.81  168.35  167.32  167.52   6450.03578   
17616       17754  1.567192e+12  167.54  169.04  165.55  168.80  22834.89586   
17617       17755  1.567195e+12  168.83  170.00  168.28  168.98  17383.03709   
17618       17756  1.567199e+12  168.93  169.09  168.25  168.37   3304.84537   
17619       17757  1.567202e+12  168.35  168.97  167.59  168.79   4958.01797   
17620       17758  1.567206e+12  168.72  169.49  167.82  168.50   6710.17888   
17621       17759  1.567210e+12  168.48  169.11  168.06  168.64   4905.14770   
17622       17760  1.567213e+12  168.66  169.49  168.50  169.11  11517.93775   
17623       17761  1.567217e+12  169.05  169.57  168.78  169.32   6651.21965   
17624       17762  1.567220e+12  169.29  169.70  168.98  169.06   7159.68047   
17625       17763  1.567224e+12  169.06  169.19  168.79  169.07   4451.88995   
17626       17764  1.567228e+12  169.07  169.23  168.70  168.98   7046.74575   
17627       17765  1.567231e+12  168.97  169.02  168.17  168.32   7734.34327   
17628       17766  1.567235e+12  168.32  168.76  168.03  168.13   4731.67967   
17629       17767  1.567238e+12  168.13  168.40  167.74  168.07   6589.11041   
17630       17768  1.567242e+12  168.07  168.24  167.49  167.99   9650.20480   
17631       17769  1.567246e+12  167.96  168.40  167.90  168.24   3507.58425   
17632  

In [4]:
df.columns

Index(['Unnamed: 0', 'Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume',
       'N_buy', 'N_sell', 'buy_amount_avg', 'sell_amount_avg',
       'buy_amount_std', 'sell_amount_std', 'price_avg', 'price_std',
       'cost_avg', 'cost_std', 'Spread_Open_Close', 'Spread_High_Low',
       'MA_Close_3', 'MA_Close_12', 'MA_Close_24', 'MA_Close_120',
       '_1d_Unnamed: 0', '_1d_Timestamp', '_1d_Open', '_1d_High', '_1d_Low',
       '_1d_Close', '_1d_Volume', '_1d_N_buy', '_1d_N_sell',
       '_1d_buy_amount_avg', '_1d_sell_amount_avg', '_1d_buy_amount_std',
       '_1d_sell_amount_std', '_1d_price_avg', '_1d_price_std', '_1d_cost_avg',
       '_1d_cost_std', '_1d_Spread_Open_Close', '_1d_Spread_High_Low',
       '_1d_MA_Close_3', '_1d_MA_Close_12', '_1d_MA_Close_24',
       '_1d_MA_Close_120', '1d_target', 'trend'],
      dtype='object')

In [5]:
cols = [
       'Open', 'High', 'Low',
       'Close', 'Volume', 'N_buy', 'N_sell', 'buy_amount_avg',
       'sell_amount_avg', 'buy_amount_std', 'sell_amount_std', 'price_avg',
       'price_std', 'cost_avg', 'cost_std', 'Spread_Open_Close',
       'Spread_High_Low', 'MA_Close_3', 'MA_Close_12', 'MA_Close_24',
       'MA_Close_120', '_1d_Unnamed: 0', '_1d_Timestamp', '_1d_Open',
       '_1d_High', '_1d_Low', '_1d_Close', '_1d_Volume', '_1d_N_buy',
       '_1d_N_sell', '_1d_buy_amount_avg', '_1d_sell_amount_avg',
       '_1d_buy_amount_std', '_1d_sell_amount_std', '_1d_price_avg',
       '_1d_price_std', '_1d_cost_avg', '_1d_cost_std',
       '_1d_Spread_Open_Close', '_1d_Spread_High_Low', '_1d_MA_Close_3',
       '_1d_MA_Close_12', '_1d_MA_Close_24', '_1d_MA_Close_120',
]

In [6]:
X = df[cols].values
y = df['trend'].values
X.shape

X_train = X[:-2160]
y_train = y[:-2160]
X_val = X[-2160:]
y_val = y[-2160:]

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_val = scaler.transform(X_val)

In [8]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(max_depth=7 ,random_state=1234, n_estimators=127) #, warm_start = True)
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=7, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=127, n_jobs=None,
            oob_score=False, random_state=1234, verbose=0,
            warm_start=False)

In [9]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
y_train_hat = clf.predict(X_train)
cm = confusion_matrix(y_train, y_train_hat)
rp = classification_report(y_train, y_train_hat)
score = accuracy_score(y_train, y_train_hat)

print(cm)
print(rp)
print(score)

[[4505 3085]
 [2175 5719]]
              precision    recall  f1-score   support

           0       0.67      0.59      0.63      7590
           1       0.65      0.72      0.68      7894

   micro avg       0.66      0.66      0.66     15484
   macro avg       0.66      0.66      0.66     15484
weighted avg       0.66      0.66      0.66     15484

0.6602944975458538


In [10]:
y_pred = clf.predict(X_val)
cm = confusion_matrix(y_val, y_pred)
rp = classification_report(y_val, y_pred)
score = accuracy_score(y_val, y_pred)

print(cm)
print(rp)
print(score)

[[590 514]
 [459 597]]
              precision    recall  f1-score   support

           0       0.56      0.53      0.55      1104
           1       0.54      0.57      0.55      1056

   micro avg       0.55      0.55      0.55      2160
   macro avg       0.55      0.55      0.55      2160
weighted avg       0.55      0.55      0.55      2160

0.549537037037037


In [11]:
N = 100
y_pred = clf.predict(X_val[:N])
cm = confusion_matrix(y_val[:N], y_pred)
rp = classification_report(y_val[:N], y_pred)
score = accuracy_score(y_val[:N], y_pred)

print(cm)
print(rp)
print(score)

[[30 24]
 [15 31]]
              precision    recall  f1-score   support

           0       0.67      0.56      0.61        54
           1       0.56      0.67      0.61        46

   micro avg       0.61      0.61      0.61       100
   macro avg       0.62      0.61      0.61       100
weighted avg       0.62      0.61      0.61       100

0.61
